[repository]
name = "hych"
authors = ["DreamMaoMao"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "699e369145fefaf1b2569c4b05a0787091680107"],
	["cbadf3e3f31ab5ad5d192daac5f2ca930d08b8fb", "699e369145fefaf1b2569c4b05a0787091680107"]
]

[hych]
description = "Window minimization plugin for hyprland,Enhancements to special workspaces"
authors = ["DreamMaoMao"]
output = "build/libhych.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build -j $(nproc)"
]